[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde           = "1.0.147"
serde_bytes     = "0.11.7"
serde_derive    = "1.0.147"
sha1            = "0.10.5"
bencode         = {version = "0.1.0", path = "../bencode"}