[package]
name = "bencode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.147"
serde_bytes = "0.11.7"
thiserror = "1.0.30"

[dev-dependencies]
serde_derive = "1.0"
hex = "0.4.3"
core = { version = "0.1.0", path = "../core" }